# Generated by Django 4.0.3 on 2022-07-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nrro_recibo', models.PositiveIntegerField()),
                ('logo', models.FileField(upload_to='')),
                ('nome_pagador', models.CharField(max_length=100)),
                ('cpf_cnpj_pagador', models.CharField(max_length=19)),
                ('nome_beneficiario', models.CharField(max_length=100)),
                ('cpf_cnpj_beneficiario', models.CharField(max_length=19)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('quantidade', models.PositiveIntegerField()),
                ('valor', models.CharField(max_length=10)),
            ],
        ),
    ]
