# Generated by Django 4.0.3 on 2022-07-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReciboPadrao',
        ),
    ]
