# Generated by Django 4.0.3 on 2022-07-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_recibopadrao_distancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopadrao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
