# Generated by Django 4.0.3 on 2022-07-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_recibopadrao_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibopadrao',
            name='celular',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
