# Generated by Django 4.0.3 on 2022-07-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_recibopadrao_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopadrao',
            name='celular',
            field=models.CharField(max_length=19),
        ),
    ]
