# Generated by Django 4.0.3 on 2022-07-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_recibopadrao_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopadrao',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
