# Generated by Django 4.0.3 on 2022-07-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_recibopadrao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopadrao',
            name='cidade',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
