# Generated by Django 4.0.3 on 2022-07-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_recibopadrao_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibopadrao',
            name='logo',
        ),
    ]
