# Generated by Django 4.0.3 on 2022-07-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dataPagamento',
            field=models.DateField(blank=True, max_length=12),
        ),
    ]
