# Generated by Django 4.0.3 on 2022-07-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_datapagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dataPagamento',
            field=models.DateField(blank=True),
        ),
    ]
