# Generated by Django 4.0.3 on 2022-07-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_datapagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dataPagamento',
        ),
    ]
