# Generated by Django 4.0.3 on 2022-07-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviços', '0001_initial'),
        ('clientes', '0005_cliente_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Serviço',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serviços.serviço'),
            preserve_default=False,
        ),
    ]
